// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelGuideDbPersistence;

#nullable disable

namespace TravelGuideDbMigration.Migrations
{
    [DbContext(typeof(TravelGuideDbContext))]
    partial class TravelGuideDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelGuideDbModels.TaskModel", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TaskId");

                    b.HasIndex("TaskName")
                        .IsUnique();

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("TravelGuideDbModels.TaskStartPoint", b =>
                {
                    b.Property<int>("TspId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TspId"));

                    b.Property<string>("StartPoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("TspId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskStartPoints", (string)null);
                });

            modelBuilder.Entity("TravelGuideDbModels.TaskStartPoint", b =>
                {
                    b.HasOne("TravelGuideDbModels.TaskModel", "TaskNavigation")
                        .WithMany("StartPoints")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskNavigation");
                });

            modelBuilder.Entity("TravelGuideDbModels.TaskModel", b =>
                {
                    b.Navigation("StartPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
